# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Combined coverage target
        target: 80%
        threshold: 2%
        # Wait for all coverage reports before reporting
        flags:
          - unit
          - integration
    patch:
      default:
        target: 70%
        threshold: 5%

# Define flags for different test types
flags:
  unit:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: true

# Ignore files from coverage report
ignore:
  - "src/**/*.test.ts"
  - "src/**/*.integration.test.ts"
  - "src/**/index.ts"
  - "dist/**"
  - "node_modules/**"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

