# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 10%

# Ignore files from coverage report
ignore:
  - "src/**/*.test.ts"
  - "src/**/*.integration.test.ts"
  - "src/**/index.ts"
  - "dist/**"
  - "node_modules/**"

# Comment configuration for PRs
comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

